backend:
  name: github
  repo: brandstackagency/michheritage
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Company Articles / Updates"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Article Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Body Content", name: "body", widget: "markdown" }
